

export let EventName = {
    GIVE_BAG_ITEM: "GIVE_BAG_ITEM",
    SET_BAG_STATE: "SET_BAG_STATE",
    SHOW_ITEM_ANIMATION_DES: "SHOW_ITEM_ANIMATION_DES",
    SHOW_GLOBAL_MASK: "SHOW_GLOBAL_MASK",
    HIDE_GLOBAL_MASK: "HIDE_GLOBAL_MASK",
    SET_BAG_ITEM_MOVE_STATE: "SET_BAG_ITEM_MOVE_STATE",
    COLLECTION_ITEM_TO_DESK: "COLLECTION_ITEM_TO_DESK",
    DESTROY_BAG: "DESTROY_BAG",
}